### ISSUE TITLE
MacOS编译错误：Package minted Error: You must have `pygmentize' installed to use this package

### ISSUE THREAD

**Issue by Wizard23333** [TJ-CSCCG/tongji-undergrad-thesis#24]
### 使用平台详情

* [ ] 线上：Overleaf
* [x] 本地：MacOS
* [ ] 本地：Windows
* [ ] 本地：各种 Linux 发行版
* [ ] 不，我使用的是 _________

### 编译日志

<details><summary><b>报错内容</b> <i>[点击打开]</i></summary>
<div>

```log
tongji-undergrad-thesis/main.tex:21: Package minted Error: You must have `pygmentize' installed to use this package.
```

</div>
</details>

### 问题描述

在macos上编译发现的一个问题，参考解决方案：https://tex.stackexchange.com/questions/48018/minted-not-working-on-mac
![截屏2023-04-24 17 45 57](https://user-images.githubusercontent.com/55119072/233961429-bda939af-c932-4c8f-a000-43d2f1f1d2df.png)

**Comment by tobiasforest** [comment]
I understand what you're saying. Could you share with me the version of macOS you're currently using, the version of TeX Live you have installed, and the method you employed to install `pygmentize`?

**Comment by skyleaworlder** [comment]
I think I understand what you mean, but personally I don't think this is a bug.

The minted package does indirectly use `pymentize`, but failing to properly install or locate `pymentize` on the computer shouldn't be considered a error of this template. However, I agree with tobiaforest's approach that this is a `docs` issue, as our template lacks explanation for minted usage.

Please let me know if I understood the issue and your intended meaning correctly.
