### ISSUE TITLE
BUG: 摘要和目录的页码问题

### ISSUE THREAD

**Issue by CookiePieWw** [TJ-CSCCG/tongji-undergrad-thesis#38]
### 使用平台详情

* [x] 线上：Overleaf
* [ ] 本地：MacOS
* [ ] 本地：Windows
* [ ] 本地：各种 Linux 发行版
* [ ] 不，我使用的是 _________

### 问题描述

使用双面打印版本时，由于 `\cleardoublepage` 不会停止页码的计数，因此摘要和目录下方的罗马数字页码将以 Ⅰ-Ⅲ-Ⅴ 的形式递增。
<p align="center">
      <img src="https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59358312/10dba58d-e4c5-4b2f-a1af-244ee5b2cea1" width="30%">
      <img src="https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59358312/88995632-90a2-4ef5-8f26-69c577c84525" width="30%">
      <img src="https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59358312/be39075b-873c-4543-b8a0-c8a7f498ced4" width="30%">
</p>

### 其他信息

可能的解决方案：使用 `\setcounter{page}` 设置正确页码。

**Comment by skyleaworlder** [comment]
我个人认为这应该算是符合我们预期的行为，因为我们计划的就是让 “中英文摘要 / 目录” 始终位于右侧。

@tobiasforest 看下 0ls 的想法是什么。

**Comment by tobiasforest** [comment]
> 我个人认为这应该算是符合我们预期的行为，因为我们计划的就是让 “中英文摘要 / 目录” 始终位于右侧。
> 
> @tobiasforest 看下 0ls 的想法是什么。

我同意 @skyleaworlder 。

这个操作是为了使 **中文摘要 / 英文摘要 / 目录 / 正文** 的起始页位于右侧，因此在 **中文摘要 / 英文摘要 / 目录 / 正文** 之间会执行一个 `\cleardoublepage` 命令。这其中会产生空白页，而且计数器不会重置。

**Comment by tobiasforest** [comment]
使用 `\setcounter{page}` 设置所谓 “正确” 页码是比较粗暴的。我们无法预知用户的中文摘要和/或英文摘要的篇幅超过一页，也不知道目录是否超过一页。

以上是我这样实现的原因。

**Comment by skyleaworlder** [comment]
0ls 的回复也是我想表达的，@CookiePieWw 同学对我们的回复有其他想法和意见吗。

如果没有的话我会给这个 issue 打上 “wontfix” 并且 close 掉。

**Comment by CookiePieWw** [comment]
感谢 @skyleaworlder 和 @tobiasforest 的回复。

我认为模板的格式应当遵从以下两个原则：
- 严格按照学校提供的 word 模板
- 按照**检查格式的同学或老师**更认可的格式

在我结束答辩提交论文时，检查格式的同学指出论文的页码需要修改；同时我认为检查格式的老师可能更认可连续的编码而非跳跃的编码。根据第二条原则，我认为模板还是应当做相应的修改。

**Comment by skyleaworlder** [comment]
有道理。模板应该在遵循学校 word 模板要求的前提下尽可能贴合用户的需求。

但同时我个人认为**学院相关负责教师在模板格式方面的思维较为敏捷、反应较为迅速、判断较为果断**，与其在统一模板上进行修改令所有用户同步，不如在文档中提出修改的方式方法。（这里又 que 了一下 #37，有时间会搞一下的

**Comment by tobiasforest** [comment]
https://tex.stackexchange.com/questions/548444/cleardoublepage-without-showing-and-incrementing-page-number

![IMG_4447](https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59563695/b5e3d067-9deb-4af3-b741-680e6a5fde92)

**Comment by tobiasforest** [comment]
Closed by 5476fcd
