### ISSUE TITLE
Use mactex instead of texlive in order to resolve tlmgr problem on macos

### ISSUE THREAD

**Issue by Nekotoxin** [TJ-CSCCG/tongji-undergrad-thesis#41]
### 文档不足之处

* 平台相关
  * MacOS Ventura 13.6.3
* 使用过程
  * tlmgr的引入和使用问题：使用brew 安装texlive后，执行sudo tlmgr update --self显示tlmgr: action not allowed in system mode: update，根据 https://tex.stackexchange.com/questions/621211/tlmgr-action-not-allowed-in-system-mode-texlive ，卸载texlive后重新安装mactex后tlmgr更新正常

###

**Comment by RizhongLin** [comment]
你好，

谢谢你的 Issue。我们正在考虑重新组织使用文档（#31）。下一个版本的文档会把 TeX Live 改成 MacTeX。
