### ISSUE TITLE
Bug：封面编译问题

### ISSUE THREAD

**Issue by GeorgeWuzy** [TJ-CSCCG/tongji-undergrad-thesis#42]
### 使用平台详情

* [√] 线上：Overleaf
* [ ] 本地：MacOS
* [ ] 本地：Windows
* [ ] 本地：各种 Linux 发行版
* [ ] 不，我使用的是 _________

### 问题描述

编译封面时，课题名称字数过多，超出下划线无法换行
![image](https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/90973495/5162316a-153d-457e-8f03-5d2318ad3497)

**Comment by RizhongLin** [comment]
Closed by #44
