### ISSUE TITLE
长标题无法自动换行

### ISSUE THREAD

**Issue by WilliamTianYe** [TJ-CSCCG/tongji-undergrad-thesis#46]
### 使用平台详情

* [x] 线上：Overleaf
* [ ] 本地：MacOS
* [ ] 本地：Windows
* [ ] 本地：各种 Linux 发行版
* [ ] 不，我使用的是 _________

### 问题描述
论文标题和副标题比较长时，不可以自动换行

### 其他信息
![image](https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59827395/654e49ba-6558-4589-937d-930b56a891a5)

**Comment by RizhongLin** [comment]
你好，请参见 #44。

更新的 Overleaf 模板还在审核当中。
