### ISSUE TITLE
如何输出word版本

### ISSUE THREAD

**Issue by lyy281726004** [TJ-CSCCG/tongji-undergrad-thesis#51]
作者好，这个latex模版对我的本科毕业论文帮助很大。使用该模板编译出pdf后，学校要求上传word源文件，请问该如何使用latex输出word文件呢？我试着安装了Pandoc，但不知道如何将整个完整的项目输出成word形式，求指点，感谢。

**Comment by RizhongLin** [comment]
你好，

感谢你对本模版的支持。

根据我的了解，目前同济 1 系统已经支持以 PDF 格式上传最终的毕业论文：

<img width="467" alt="image" src="https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/59563695/398e39f3-78a8-4c14-b7be-0e7b01ee229e">

如果你确实需要将本模版生成的 PDF 转换为 Word 文档，有以下几种可选方法：

1. 使用 Adobe Acrobat 将 PDF 导出为 Microsoft Word 文件；
2. 使用 Microsoft Word 直接打开 PDF 后，将其另存为 Word 格式；
3. 使用第三方 PDF 转换工具（如 [PDF2Go](https://www.pdf2go.com/pdf-to-word)）进行转换；
4. 使用 pandoc 将 $\LaTeX$ 代码直接转换为 Word 文档，不过由于本模版的代码结构复杂，这种方法需要使用复杂的 pandoc 命令，建议你自行查询相关的命令。

希望这些方法能帮助到你。

**Comment by lyy281726004** [comment]
收到，感谢回复
---- 回复的原邮件 ----
发件人Rizhong ***@***.***>发送日期2024年06月01日 14:10 ***@***.***> ***@***.***>,
***@***.***>主题Re: [TJ-CSCCG/tongji-undergrad-thesis] 如何输出word版本 (Issue #51)
你好，
感谢你对本模版的支持。
根据我的了解，目前同济 1 系统已经支持以 PDF 格式上传最终的毕业论文：
image.png (view on web) 如果你确实需要将本模版生成的 PDF 转换为 Word 文档，有以下几种可选方法：
使用 Adobe Acrobat 将 PDF 导出为 Microsoft Word 文件；
使用 Microsoft Word 直接打开 PDF 后，将其另存为 Word 格式；
使用第三方 PDF 转换工具（如 PDF2Go）进行转换；
使用 pandoc 将 $\LaTeX$ 代码直接转换为 Word 文档，不过由于本模版的代码结构复杂，这种方法需要使用复杂的 pandoc 命令，建议你自行查询相关的命令。
希望这些方法能帮助到你。
