### ISSUE TITLE
英文摘要的标题该如何修改？

### ISSUE THREAD

**Issue by lyy281726004** [TJ-CSCCG/tongji-undergrad-thesis#55]
如图，英文摘要的标题是"Thesis Template"，在abstract中未找到能够修改的地方。
![Uploading 英文摘要.png…]()

**Comment by lyy281726004** [comment]
![英文摘要](https://github.com/TJ-CSCCG/tongji-undergrad-thesis/assets/62351377/8c7dbd14-6842-4eee-8996-e994361c11f1)

**Comment by RizhongLin** [comment]
你好，你可以在 `sections/frontcover.tex` 
修改英文标题。

**Comment by lyy281726004** [comment]
收到，感谢
