### ISSUE TITLE
Overleaf平台使用模板会报错编译超时，可通过直接拉取模板（未修改状态下）复现

### ISSUE THREAD

**Issue by wang-jt** [TJ-CSCCG/tongji-undergrad-thesis#56]
### 使用平台详情

* [x] 线上：Overleaf
* [ ] 本地：MacOS
* [ ] 本地：Windows
* [ ] 本地：各种 Linux 发行版
* [ ] 不，我使用的是 _________

### 编译日志

<details><summary><b>报错内容</b> <i>[点击打开]</i></summary>
<div>

Your compile timed out
Your project exceeded the compile timeout limit on our free plan.

Upgrade to get 12x more compile time (plus additional collaborators, document history, track changes, and more).

</div>
</details>

### 问题描述

如题，Overleaf平台使用模板会报错编译超时，可通过直接拉取模板（未修改状态下）复现，该问题不是由于图片太多或字数太长引起，即使在只有一章（三页），并且无图的情况下仍会产生。

**Comment by RizhongLin** [comment]
你好，谢谢你的 Issue！

关于编译时长超过 Overleaf 免费版限制的问题，目前只能通过本地编译来解决。

如果希望继续在 Overleaf 免费版上编译，可以尝试：

- **参考文献**：需要引用时，可以将 `biblatex` 改为 `bibtex` 或禁用 `biblatex`，因为 `biblatex` 需要至少两次编译来生成文献列表，增加编译时间。
  
- **代码展示**：需要展示代码时，可以将 `minted` 替换为其他代码高亮工具或直接禁用，因为 `minted` 依赖 `Python` 和 `Pygments`，编译较慢。

希望这些建议能有所帮助。谢谢！
